### ISSUE TITLE
adding goal text string to file name bring errors for long goals.

### ISSUE THREAD

**Issue by PiotrEsse** [yanniedog/crewai-autocrew#5]
Hi, 
adding goal description to a filename gives error for long goals.
Idea is perfect but brings error as users cant use long texts.
<img width="1032" alt="image" src="https://github.com/yanniedog/crewai-autocrew/assets/42764623/31459049-7683-4fb3-8e18-52e9fc20bbae">

Its in line #31
I would trunctate this to , lets say, 10 letters.

**Comment by yanniedog** [comment]
Nice pickup. Yep, this will be an easy fix. I'll do it tomorrow. Thanks again 👍

**Comment by yanniedog** [comment]
Also, it looks like you're using an old version of the script

**Comment by PiotrEsse** [comment]
> Also, it looks like you're using an old version of the script

yes, it was older ;-)

**Comment by yanniedog** [comment]
Problem: need to ensure the "overall_goal" component of the csv/py filename does not exceed 30 characters.

The simple solution:
- just truncate the overall_goal string after the 30th character

The sophisticated solution:
- if overall_goal is >30 characters, then before saving the csv/py, make an additional query to the LLM to summarise it as follows:
"provide a concise, precise version of the string "(overall_goal)", so that it's total length is no longer than 30 characters. Your response must strictly contain only your shortened version of the string, enclosed with double quotes. Do not add anything else to your response."

**Comment by yanniedog** [comment]
The current version now inserts only the first 50 characters of overall_goal into the CSV / PY filenames
